// Company contact list (from EB CONTACT LIST 07-17-2026) — email -> display
// name. Used to backfill a user's name when Entra provides no name claim and
// the user hasn't typed one, so accounts never show a bare email as the name.
// Keys are lowercase. Regenerate from the contact list when people change.
const NAME_BY_EMAIL = {
  '02scottism@gmail.com': 'Scott Braswell',
  '36watkins@gmail.com': 'Mark Thompson',
  'aaperez8918@gmail.com': 'Alex Perez',
  'ambriz34@icloud.com': 'Juan Ambriz',
  'amzad@earthbasics.net': 'Amzad Hosein',
  'anrpilotcar@gmail.com': 'Anthony Robles',
  'antfilms99@gmail.com': 'Anthony Gonzalez',
  'armbsg740@gmail.com': 'Arturo Munoz',
  'beardman5@aol.com': 'Wild Bill Beardman',
  'bigdogbait@gmail.com': 'Bryan Robert Orms',
  'blakedalen@gmail.com': 'Blake Dalen',
  'bluttrell@earthbasics.net': 'Brian Luttrell',
  'bntz16r@gmail.com': 'Ramiro Benitez',
  'bob@earthbasics.net': 'Robert Pecoy',
  'brian@earthbasics.net': 'Brian Colin',
  'bryan.wilcox2018@icloud.com': 'Bryan Wilcox',
  'bufordp32@gmail.com': 'Brian Howe',
  'bullrun35@icloud.com': 'Jesus Maldonado',
  'calfrider07@yahoo.com': 'Clayton Odermatt',
  'caseymckinney903@yahoo.com': 'Casey McKinney',
  'catiany@earthbasics.net': 'Catiany Hansen',
  'chales2000@hotmail.com': 'Raymundo Quintero',
  'cholman@earthbasics.net': 'Craig Holman',
  'ciscogomezjr84@icloud.com': 'Francisco Gomez',
  'crgrader@gmail.com': 'Corey Read',
  'cruz21313_@hotmail.com': 'Chaze Cruz',
  'daveb@earthbasics.net': 'Dave Blood',
  'david96326801@gmail.com': 'David Campos',
  'dezmin1218@gmail.com': 'Dezmin Morales',
  'diegonavarro0606@gmail.com': 'Diego Navarro',
  'elijahreyalcala95@yahoo.com': 'Elijah Alcala',
  'ericm@earthbasics.net': 'Eric Martinez',
  'erics@earthbasics.net': 'Eric Sladen',
  'erikydaniel2012@gmail.com': 'Erik Renteria',
  'francojuan836@gmail.com': 'Juan Aguirre',
  'gabriel@earthbasics.net': 'Gabriel Arriaga',
  'gpecoy@earthbasics.net': 'Garry Pecoy III',
  'greywolf4242@live.com': 'Antonio Alcaraz',
  'haley@earthbasics.net': 'Haley Gardner',
  'iphone426@gmail.com': 'Tony Blood',
  'jack@earthbasics.net': 'Jack Rose',
  'jacobegarcia0313@yahoo.com': 'Jacob Garcia',
  'jasonb@earthbasics.net': 'Jason Bowers',
  'jennifer@earthbasics.net': 'Jennifer Zeigler',
  'jlemmon@earthbasics.net': 'Jason Lemmon',
  'jluisb012902@gmail.com': 'Jose Bermudez',
  'kbcvance86@gmail.com': 'Kyle Vance',
  'knicholson@earthbasics.net': 'Kim Nicholson',
  'leerogers2024@icloud.com': 'Lee Rogers',
  'lemus.kevin1320@gmail.com': 'Kevin Lemus',
  'leonel96949@yahoo.com': 'Leonel Montalvan',
  'leoz44165@gmail.com': 'Tony Gutierrez',
  'lheinle17@gmail.com': 'Lucas Heinle',
  'liz@earthbasics.net': 'Liz Chase',
  'manuelolivier76@yahoo.com': 'Manny Olivier',
  'marcos13ambriz@gmail.com': 'Marcos Ambriz',
  'markascott5@gmail.com': 'Mark Scott',
  'masonspangler83@gmail.com': 'Mason Spangler',
  'moe.nicholas92@gmail.com': 'Nicholas Moeller',
  'ncowles@earthbasics.net': 'Nick Cowles',
  'newt3.b@gmail.com': 'Willis Newton',
  'nicolate_7@yahoo.com': 'Nick Castilleja',
  'noah.mcneely0824@gmail.com': 'Noah McNeely',
  'nohel@earthbasics.net': 'Nohel Mejia',
  'omar@earthbasics.net': 'Omar Dominguez',
  'patrick.morbitzer@gmail.com': 'Patrick Morbitzer',
  'payton.wright262626@gmail.com': 'Payton Wright',
  'phillip@earthbasics.net': 'Phillip Watts',
  'rachelpecoy@gmail.com': 'Rachel Pecoy',
  'reece9015@gmail.com': 'Jared Reese',
  'reessorensen0@gmail.com': 'Rees Sorensen',
  'rkuykendall@earthbasics.net': 'Riley Kuykendall',
  'rosalyn16camarillo@icloud.com': 'Jose Luis Camarillo',
  'scottystephensfmx@gmail.com': 'Roberto Villa',
  'sjmarsteen@gmail.com': 'Steve Marsteen',
  't_rev_2010@yahoo.com': 'Trevor Carr',
  'tina@earthbasics.net': 'Tina Woodside',
  'travis@earthbasics.net': 'Travis Pecoy',
  'ua3xrico.com@outlook.com': 'Enrico Mares',
  'wbeardman86@gmail.com': 'Billy Beardman',
  'wilson.ron2.rw@gmail.com': 'Ron Wilson',
};

module.exports = { NAME_BY_EMAIL };
